language: go
sudo: false
go:
  - 1.5.2
  - tip
env:
  - GOARCH=amd64
  - GO15VENDOREXPERIMENT=1
notifications:
  email:
    on_success: change
    on_failure: always
script: go get github.com/2fanginx && go test
