language: go
sudo: false
go:
  - 1.5.2
  - tip
env:
  - GOARCH=amd64
  - GO15VENDOREXPERIMENT=1
notifications:
  email:
    on_success: change
    on_failure: always
gobuild_args: -ldflags "-X github.com/lstep/2fanginx/server.buildst=`date -u '+%Y-%m-%dT%I:%M:%S'` -X github.com/lstep/2fanginx/server.githash=`git rev-parse HEAD`"
script: go get github.com/lstep/2fanginx && go test
